#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;

define('LARAVEL_START', microtime(true));

// Registra o Autoloader do Composer
require __DIR__.'/vendor/autoload.php';

// Inicializa a aplicação Laravel e executa o comando de console
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new Symfony\Component\Console\Input\ArgvInput);

exit($status);